### ISSUE TITLE
I have error about .net sdk

### ISSUE THREAD

**Issue by craftiz** [zlatanov/windows-screen-recorder#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1141	Unable to resolve the .NET SDK version as specified in the global.json located at C:\Users\LeventilhanCloudCan\Downloads\windows-screen-recorder-master\windows-screen-recorder-master\global.json.	WindowsScreenRecorder	C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	127

**Comment by zlatanov** [comment]
I haven't updated the project recently. Currently it uses .NET SDK 6.0.300. You can download it [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.311-windows-x64-installer).

Alternatively, you can edit the global.json file and set whichever version you have installed. You can check by using the following command in your terminal:

```cmd
dotnet --list-sdks
```

**Comment by craftiz** [comment]
![image](https://github.com/zlatanov/windows-screen-recorder/assets/645982/f113af88-f8cb-4c01-a968-fd66c0f2a97f)

**Comment by zlatanov** [comment]
You seem to have 6.0.408 and not 6.0.300. Change to global.json file in the root directory of the project to look like this:

```json
{
    "sdk": {
        "version": "6.0.408"
    },
    "tools": {
        "dotnet": "6.0.408"
    }
}
```

**Comment by craftiz** [comment]
thank youu fixed.
